import express from "express";
import { connectDB } from "./config/db.js";
import notesRouter from "./routes/notesRoutes.js ";
import RateLimitter from "./middleware/rateLimitter.js";
import cors from "cors" 

const app = express();
const PORT = 3000;

// Middleware for parsing JSON request bodies
app.use(express.json());

// 1. FIX: Use CORS before Rate Limiter and Routes
// This ensures the Access-Control-Allow-Origin header is present
// on all responses, including those generated by the rate limiter.
app.use(cors({origin:"http://localhost:5173"}));

// 2. Application of the Rate Limiter Middleware
app.use(RateLimitter); 

// 3. Application of the Notes Router
app.use("/api/notes", notesRouter);

// Connect to Database and start server
connectDB().then(() => {
  // Start the server
  app.listen(PORT, () => {
    console.log(`🚀 Server running on http://localhost:${PORT}`);
  });
});